name: doc
on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # 此处每一个name对应着一个Action，具体执行逻辑已被提供者进行封装，暴露给用户的只是需要用户需要关心和配置的
            # 从master上获取最新代码
            - name: Checkout
              uses: actions/checkout@master

            - name: Install
              run: npm install

            # 部署
            - name: ssh deploy
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
                  ARGS: '-avz --delete'
                  # 涉及偏安全隐私的信息，不要明文暴露在此文件中，因为repo很可能是公开的，会被所有人看见
                  # ${{ ... }} 会应用你在对应项目设置中，配置的对应serets的键值信息，从而保护私密信息不被看到
                  REMOTE_HOST: ${{ secrets.HOST }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  TARGET: '/home/vue3-doc/'
